baseURL = '//dataspeculations.org/'
languageCode = 'en-us'
title = 'Data Speculations'
theme = "gohugo-theme-ananke"
canonifyURLS = true
enableRobotsTXT = true
[menu]
[[menu.main]]
  name = 'About'
  pageRef = '/about/_index.md'
  weight = 1
[[menu.main]]
  name = 'People'
  pageRef = '/people'
  weight = 2
[[menu.main]]
  name = 'Scholarship'
  pageRef = '/scholarship/'
  weight = 3
